app = 'event-post-api-dark-leaf-3702'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[env]
  PORT = "3000"
  RAILS_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  # ğŸ‘‡ æ¥ç¶šã‚’ã‚ˆã‚Šç¢ºå®Ÿã«ã™ã‚‹ãŸã‚ã®ãƒã‚§ãƒƒã‚¯ã‚’è¿½åŠ 
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[vm]]
  memory_mb = 1024
  cpus = 1

[deploy]
  release_command = "/rails/bin/rails db:migrate"